default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: "123456"
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: pro_development
test:
  <<: *default
  database: pro_test
production:
  <<: *default
  database: pro_production
  username: pro
  password: <%= ENV['PRO_DATABASE_PASSWORD'] %>
