# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c244762bf4816a019b057bf31e74fa5e76934352c73380379b360b6e0e045eb33b959a92f518db5260f9a5ac658cf9ebe7b943763f5bd0d552b8132a494f4081

test:
  secret_key_base: 93cc16f98e16d15a64a427c67068aebb4e3972b093964f2807004fc7b0c23e025cf92dabcf3e8c58c63af6bed625aff676225be6db73ca3bb6f31d2ed9e9174b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
